// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VisiitkaartBackend.Data;

namespace VisiitkaartBackend.Migrations
{
    [DbContext(typeof(VisiitkaartDbContext))]
    [Migration("20180620105037_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VisiitkaartBackend.Data.Models.User", b =>
                {
                    b.Property<string>("Email")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(200);

                    b.Property<byte>("RoleValue");

                    b.HasKey("Email");

                    b.ToTable("Users");

                    b.HasData(
                        new { Email = "admin@visiitkaart.ee", PasswordHash = "2iYX3yd5wjY9ZErZzudZ2lXy7MvR46Wb/aHMkGYXlbsVja81", RoleValue = (byte)128 }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
