// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VisiitkaartBackend.Data;

namespace VisiitkaartBackend.Migrations
{
    [DbContext(typeof(VisiitkaartDbContext))]
    partial class VisiitkaartDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VisiitkaartBackend.Data.Models.User", b =>
                {
                    b.Property<string>("Email")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("PasswordHash");

                    b.HasKey("Email");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("VisiitkaartBackend.Data.Models.UserRole", b =>
                {
                    b.Property<string>("UserEmail");

                    b.Property<byte>("RoleValue");

                    b.HasKey("UserEmail", "RoleValue");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("VisiitkaartBackend.Data.Models.UserRole", b =>
                {
                    b.HasOne("VisiitkaartBackend.Data.Models.User", "User")
                        .WithMany("Roles")
                        .HasForeignKey("UserEmail")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
